<#
.SYNOPSIS
    Generates a Sharegate-ready OneDrive source → destination mapping CSV
    by matching source and destination OneDrive export CSVs generated by Sharegate.

.DESCRIPTION
    No Graph connection required. Matches purely from the two exported CSV files.
    Produces three output files:
      - OneDrive_Mapping_Sharegate.csv        → Ready for Sharegate import (matched only)
      - OneDrive_Mapping_Unmatched.csv        → Users not found in target CSV (manual action required)
      - OneDrive_Mapping_NonUserAccounts.csv  → Functional/service accounts (migration decision required)

.PARAMETER SourceCsvPath
    Path to the source OneDrive export CSV (no header — columns: Name, URL).

.PARAMETER TargetCsvPath
    Path to the destination OneDrive export CSV (header row: Title, Site address).

.PARAMETER OutputFolder
    Folder where output CSVs will be written. Defaults to current directory.

.EXAMPLE
    .\New-OneDriveMappingFile.ps1 -SourceCsvPath ".\source-onedrive.csv" -TargetCsvPath ".\destination-onedrive.csv" -OutputFolder ".\Output"
#>

[CmdletBinding(SupportsShouldProcess)]
param (
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ })]
    [string]$SourceCsvPath,

    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ })]
    [string]$TargetCsvPath,

    [Parameter()]
    [string]$OutputFolder = (Get-Location).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Non-user account keywords ─────────────────────────────────────────────────
# Add company-specific keywords to filter out functional/service accounts
# Example: @('sysadmin','sharepoint admin','teams room','service account')
$NonUserKeywords = @()

# ── Load source CSV (no header row) ──────────────────────────────────────────
Write-Host "`n[INFO] Loading source CSV: $SourceCsvPath" -ForegroundColor Cyan
$sourceRows = Import-Csv -Path $SourceCsvPath -Header @('DisplayName','SourceSite') -Encoding Default
Write-Host "[INFO] $($sourceRows.Count) source entries loaded."

# ── Load target CSV (has header: Title, Site address) ───────────────────────────
Write-Host "[INFO] Loading target CSV: $TargetCsvPath" -ForegroundColor Cyan
$targetRows = Import-Csv -Path $TargetCsvPath -Encoding Default

# Build lookup: DisplayName (lower) → Site URL
$targetLookup = @{}
foreach ($r in $targetRows) {
    $key = $r.Title.Trim().ToLower()
    if (-not $targetLookup.ContainsKey($key)) {
        $url = $r.'Site address'.Trim()
        if ($url -ne '') { $targetLookup[$key] = $url.TrimEnd('/') + '/' }
    }
}
Write-Host "[INFO] $($targetLookup.Count) target OneDrive accounts indexed."

# ── Match source → target ─────────────────────────────────────────────────────
$matched          = [System.Collections.Generic.List[PSCustomObject]]::new()
$unmatchedUsers   = [System.Collections.Generic.List[PSCustomObject]]::new()
$nonUserAccounts  = [System.Collections.Generic.List[PSCustomObject]]::new()

foreach ($row in $sourceRows) {
    $name    = $row.DisplayName.Trim()
    $srcUrl  = $row.SourceSite.Trim()
    $nameLow = $name.ToLower()

    # Skip blank rows
    if ([string]::IsNullOrWhiteSpace($name)) { continue }

    # Classify non-user accounts first
    $isNonUser = $false
    foreach ($kw in $NonUserKeywords) {
        if ($nameLow -eq $kw -or $nameLow.StartsWith($kw + ' ') -or $nameLow -eq $kw.Replace(' ','')) {
            $isNonUser = $true; break
        }
    }

    if ($isNonUser) {
        $nonUserAccounts.Add([PSCustomObject]@{
            DisplayName     = $name
            SourceSite      = $srcUrl
            DestinationSite = ''
            Notes           = 'Non-user / functional account — migration decision required'
        })
        continue
    }

    # Exact display name match
    $dstUrl    = $null
    $matchType = $null

    if ($targetLookup.ContainsKey($nameLow)) {
        $dstUrl    = $targetLookup[$nameLow]
        $matchType = 'Exact'
    }

    # First-name + last-name partial fallback
    if (-not $dstUrl) {
        $parts = $name -split '\s+'
        if ($parts.Count -ge 2) {
            $first = $parts[0].ToLower()
            $last  = $parts[-1].ToLower()
            $hit   = $targetLookup.Keys | Where-Object { $_ -like "*$last*" -and $_ -like "*$first*" } | Select-Object -First 1
            if ($hit) {
                $dstUrl    = $targetLookup[$hit]
                $matchType = "Fuzzy (name variant: '$hit')"
            }
        }
    }

    if ($dstUrl) {
        $matched.Add([PSCustomObject]@{
            SourceSite      = $srcUrl
            DestinationSite = $dstUrl
            DisplayName     = $name
            MatchType       = $matchType
        })
    } else {
        $unmatchedUsers.Add([PSCustomObject]@{
            DisplayName     = $name
            SourceSite      = $srcUrl
            DestinationSite = ''
            Notes           = 'NOT FOUND in target tenant — manual lookup required'
        })
    }
}

# ── Report summary ────────────────────────────────────────────────────────────
Write-Host "`n── Match Summary ──────────────────────────────────────────" -ForegroundColor Green
Write-Host "  Matched (Sharegate-ready) : $($matched.Count)"          -ForegroundColor Green
Write-Host "  Unmatched real users      : $($unmatchedUsers.Count)"   -ForegroundColor Yellow
Write-Host "  Non-user accounts         : $($nonUserAccounts.Count)"  -ForegroundColor Yellow

if ($unmatchedUsers.Count -gt 0) {
    Write-Host "`n[WARN] The following users were NOT found in the target tenant:" -ForegroundColor Yellow
    $unmatchedUsers | ForEach-Object { Write-Host "  ⚠  $($_.DisplayName) — $($_.SourceSite)" -ForegroundColor Yellow }
    Write-Host "`n  [ACTION REQUIRED] Verify these users are provisioned in the target tenant." -ForegroundColor Yellow
    Write-Host "  Run Get-OneDriveInventory.ps1 against target and re-run this script, or" -ForegroundColor Yellow
    Write-Host "  populate DestinationSite manually in OneDrive_Mapping_Unmatched.csv." -ForegroundColor Yellow
}

if ($PSCmdlet.ShouldProcess($OutputFolder, 'Write output CSV files')) {

    if (-not (Test-Path $OutputFolder)) {
        New-Item -ItemType Directory -Path $OutputFolder | Out-Null
    }

    $sharegateFile    = Join-Path $OutputFolder 'OneDrive_Mapping_Sharegate.csv'
    $unmatchedFile    = Join-Path $OutputFolder 'OneDrive_Mapping_Unmatched.csv'
    $nonUserFile      = Join-Path $OutputFolder 'OneDrive_Mapping_NonUserAccounts.csv'

    # Build unmatched/non-user rows in Sharegate column format (destination blank)
    $unmatchedForSharegate = $unmatchedUsers | ForEach-Object {
        [PSCustomObject]@{
            SourceSite      = $_.SourceSite
            DestinationSite = ''
            DisplayName     = $_.DisplayName
            MatchType       = 'Unmatched — destination required'
        }
    }
    $nonUserForSharegate = $nonUserAccounts | ForEach-Object {
        [PSCustomObject]@{
            SourceSite      = $_.SourceSite
            DestinationSite = ''
            DisplayName     = $_.DisplayName
            MatchType       = 'Non-user account — migration decision required'
        }
    }

    @($matched) |
        Export-Csv -Path $sharegateFile -NoTypeInformation -Encoding UTF8
    $unmatchedUsers  | Export-Csv -Path $unmatchedFile -NoTypeInformation -Encoding UTF8
    $nonUserAccounts | Export-Csv -Path $nonUserFile   -NoTypeInformation -Encoding UTF8

    Write-Host "`n── Output Files ───────────────────────────────────────────" -ForegroundColor Cyan
    Write-Host "  ✅ $sharegateFile"  -ForegroundColor Green
    Write-Host "  ⚠  $unmatchedFile" -ForegroundColor Yellow
    Write-Host "  ℹ  $nonUserFile"   -ForegroundColor Cyan

    Write-Host "`n[INFO] Load OneDrive_Mapping_Sharegate.csv into Sharegate:"
    Write-Host "       Migrate → OneDrive → Import users from file → select SourceSite / DestinationSite columns."
}

Write-Host "`n[DONE]" -ForegroundColor Green
